/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mh.gui;

import com.mh.biz.MaquinaHelados;
import com.mh.utils.Utils;

/**
 *
 * @author dev
 */
public class InsertarMonedas extends javax.swing.JDialog {

    private MoneyUpdateListener listener;

    private MaquinaHelados mh;

    public void setMoneyUpdateListener(MoneyUpdateListener listener) {
        this.listener = listener;
    }

    /**
     * Creates new form InsertarMonedas
     */
    public InsertarMonedas(java.awt.Frame parent, boolean modal, MaquinaHelados mh) {
        super(parent, modal);
        this.mh = mh;
        initComponents();
        actualizarMostrador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add50Cts = new javax.swing.JButton();
        add10Cts = new javax.swing.JButton();
        add20Cts = new javax.swing.JButton();
        addOneEuro = new javax.swing.JButton();
        addTwoEuro = new javax.swing.JButton();
        IntroDinero = new javax.swing.JButton();
        DevoDinero = new javax.swing.JButton();
        MostradorDinero = new javax.swing.JTextField();
        add5Cts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        add50Cts.setText("0,5€");
        add50Cts.setPreferredSize(new java.awt.Dimension(80, 80));
        add50Cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add50CtsActionPerformed(evt);
            }
        });

        add10Cts.setText("0,10€");
        add10Cts.setPreferredSize(new java.awt.Dimension(80, 80));
        add10Cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add10CtsActionPerformed(evt);
            }
        });

        add20Cts.setText("0,20€");
        add20Cts.setPreferredSize(new java.awt.Dimension(80, 80));
        add20Cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add20CtsActionPerformed(evt);
            }
        });

        addOneEuro.setText("1€");
        addOneEuro.setPreferredSize(new java.awt.Dimension(80, 80));
        addOneEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneEuroActionPerformed(evt);
            }
        });

        addTwoEuro.setText("2€");
        addTwoEuro.setPreferredSize(new java.awt.Dimension(80, 80));
        addTwoEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTwoEuroActionPerformed(evt);
            }
        });

        IntroDinero.setText("Introducir");
        IntroDinero.setPreferredSize(new java.awt.Dimension(100, 35));
        IntroDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroDineroActionPerformed(evt);
            }
        });

        DevoDinero.setText("Devolver");
        DevoDinero.setPreferredSize(new java.awt.Dimension(100, 35));
        DevoDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevoDineroActionPerformed(evt);
            }
        });

        MostradorDinero.setEditable(false);
        MostradorDinero.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        MostradorDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostradorDineroActionPerformed(evt);
            }
        });

        add5Cts.setText("0,05€");
        add5Cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add5CtsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(MostradorDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(addTwoEuro, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(IntroDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(DevoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add10Cts, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(add50Cts, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add20Cts, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(addOneEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(add5Cts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MostradorDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addTwoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addOneEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntroDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DevoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add50Cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add20Cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add10Cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add5Cts, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addTwoEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTwoEuroActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 2.0);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }


    }//GEN-LAST:event_addTwoEuroActionPerformed

    private void addOneEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneEuroActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 1.0);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
    }//GEN-LAST:event_addOneEuroActionPerformed

    private void add50CtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add50CtsActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 0.5);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
    }//GEN-LAST:event_add50CtsActionPerformed


    private void add20CtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add20CtsActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 0.20);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
    }//GEN-LAST:event_add20CtsActionPerformed

    private void add10CtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add10CtsActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 0.10);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }

    }//GEN-LAST:event_add10CtsActionPerformed

    private void actualizarMostrador() {
        
        MostradorDinero.setText(String.format("%.2f", mh.getMonedero()) + "€");
    }

    private void DevoDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevoDineroActionPerformed
        // TODO add your handling code here:

        mh.setMonedero(0.0);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
        
        
    }//GEN-LAST:event_DevoDineroActionPerformed

    private void IntroDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroDineroActionPerformed
        // TODO add your handling code here:
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
        dispose();
    }//GEN-LAST:event_IntroDineroActionPerformed

    private void MostradorDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostradorDineroActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_MostradorDineroActionPerformed

    private void add5CtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add5CtsActionPerformed
        // TODO add your handling code here:
        mh.setMonedero(mh.getMonedero() + 0.05);
        actualizarMostrador();
        if (listener != null) {
            listener.onMoneyUpdated(mh.getMonedero());
        }
        
    }//GEN-LAST:event_add5CtsActionPerformed

    public interface MoneyUpdateListener {

        void onMoneyUpdated(double money);
    }

    private String mostrarDinero(MaquinaHelados mh) {
        double dinero = mh.getMonedero();
        String dineros = dinero + "Euros";

        return dineros;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(InsertarMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(InsertarMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(InsertarMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(InsertarMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Crear una instancia de MaquinaHelados aquí
            MaquinaHelados mh = new MaquinaHelados();
            InsertarMonedas dialog = new InsertarMonedas(new javax.swing.JFrame(), true, mh);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DevoDinero;
    private javax.swing.JButton IntroDinero;
    private javax.swing.JTextField MostradorDinero;
    private javax.swing.JButton add10Cts;
    private javax.swing.JButton add20Cts;
    private javax.swing.JButton add50Cts;
    private javax.swing.JButton add5Cts;
    private javax.swing.JButton addOneEuro;
    private javax.swing.JButton addTwoEuro;
    // End of variables declaration//GEN-END:variables
}
